services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    ports:
      - "8883:8883"
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - /opt/certs:/mosquitto/config/certs:ro
    networks:
      - iot-net
    healthcheck:
      test: [
        "CMD-SHELL",
        "mosquitto_sub -h localhost -p 1884 -t '$$SYS/#' -C 1 -W 5 >/dev/null 2>&1"
      ]
      interval: 20s
      timeout: 8s
      retries: 5
      start_period: 60s


networks:
  iot-net:
    external: true
