apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxDB
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: home
      defaultBuckets: sensors
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
