[agent]
  interval = "10s"
  round_interval = true
  # Explicitly set to current default to silence warning
  # Change to true now if you want Telegraf v1.40 behavior
  skip_processors_after_aggregators = false

[[inputs.mqtt_consumer]]
  servers = ["ssl://mosquitto:8883"]
  topics = ["sensors/temperature"]
  client_id = "telegraf"
  qos = 1

  tls_ca = "/etc/telegraf/certs/ca.crt"
  tls_cert = "/etc/telegraf/certs/raspi.crt"
  tls_key = "/etc/telegraf/certs/raspi.key"
  tls_server_name = "mosquitto"
  insecure_skip_verify = false

  data_format = "json_v2"
  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "sensorwerte"
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "temperatur"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "home"
  bucket = "sensors"

